# Generated by Django 5.0.1 on 2024-01-31 06:56

import server.models
import server.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0002_category_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="banner",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=server.models.server_banner,
                validators=[server.validators.image_extension],
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="icon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=server.models.server_icon,
                validators=[
                    server.validators.icon_size,
                    server.validators.image_extension,
                ],
            ),
        ),
    ]
